services:  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: '<TIMEZONE>'
      FTLCONF_webserver_api_password: '<PASSWORD>'
      FTLCONF_dns_listeningMode: all
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  # watchtower:
  #   image: v2tec/watchtower
  #   container_name: watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  
  # sjuben:
  #   image: spark156/money-wasted-on-swap-fiets-counter:latest
  #   restart: unless-stopped
  #   networks:
  #     - caddy
  
# hboi-domeinbeschrijving:
#   image: spark156/hboi-domeinbeschrijving:latest
#   restart: unless-stopped
#   networks:
#     - caddy

# cv:
#   image: spark156/curriculum-vitea:latest
#   restart: unless-stopped
#   networks:
#     - caddy

# vue-to-do-app:
#   image: spark156/vue-to-do-app-frontend:latest
#   restart: unless-stopped
#   networks:
#     - caddy

# portfolio:
#   image: spark156/portfolio-frontend:latest
#   restart: unless-stopped
#   networks:
#     - caddy

networks:
  default:
    external: true
    name: proxy