# ATTENTION
# you must rewrite all evironment variables that contain a variable in brackets: " {variable} "
# replace everything between the quotes with your variable 

version: "3.8"

services:  
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  sjuben:
    image: spark156/money-wasted-on-swap-fiets-counter:latest
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: sjuben.lucabergman.nl
      caddy.reverse_proxy: "{{upstreams 80}}"
    
  hboi-domeinbeschrijving:
    image: spark156/hboi-domeinbeschrijving:latest
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: hboi.lucabergman.nl
      caddy.reverse_proxy: "{{upstreams 80}}"

  cv:
    image: spark156/curriculum-vitea:latest
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: cv.lucabergman.nl
      caddy.reverse_proxy: "{{upstreams 80}}"


networks:
  caddy:
    external: true