version: "3"

services:
  traefik:
    image: traefik:2.2
    container_name: traefik
    restart: unless-stopped
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    networks: 
      - web
  
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

      
networks:
  web: 
