version: "3"

services:
  traefik:
    image: traefik:2.2
    container_name: traefik
    restart: unless-stopped
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    networks: 
      - web
  
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sjuben:
    image: spark156/money-wasted-on-swap-fiets-counter
    container_name: sjuben
    restart: unless-stopped
    networks: 
      - web
    labels:
      - traefik.http.routers.sjuben.rule=Host(`sjuben.lucabergman.nl`)
      - traefik.http.routers.sjuben.tls=true
      - traefik.http.routers.sjuben.tls.certresolver=lets-encrypt
      - traefik.port=80

  bhoi-domeinbeschrijving:
    image: spark156/hboi-domeinbeschrijving
    container_name: hboi-domeinbeschrijving
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.http.routers.hboi.rule=Host(`hboi.lucabergman.nl`)
      - traefik.http.routers.hboi.tls=true
      - traefik.http.routers.hboi.tls.certresolver=lets-encrypt
      - traefik.port=80

  cv:
    image: spark156/curriculum-vitea
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.http.routers.hboi.rule=Host(`cv.lucabergman.nl`)
      - traefik.http.routers.hboi.tls=true
      - traefik.http.routers.hboi.tls.certresolver=lets-encrypt
      - traefik.port=80

      
networks:
  web: 
